# configData.yaml

# SDC生产数据库
database:
  # 数据库地址
  host: cstc-sdc.rwlb.polardb-pg-public.rds.aliyuncs.com
  # 端口号
  port: 1921
  # database
  database: sdc-prd
  # 用户名
  username: uat
  # 密码
  password: 5RsyXDEcUa

file_path:
  # 用例数据路径
  test_case: testCase/case_data.xls
  # allure报告生成路径
  report: report/
  # 文件日志
  log: log

auth_login:
  # api_key的用户和密码
  api_key:
    appId: 00015412_APP01
    appSecret: rvdkc20kimy5w1jgt9wqhjmpteokfq